﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hdp.CoreRx.Models;
using Refit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace Hdp.CoreRx.Services
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIHDPApiService : IHDPApiService
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIHDPApiService(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<List<Article>> GetArticles(DeviceType deviceType)
        {
            var arguments = new object[] { deviceType };
            return (Task<List<Article>>) methodImpls["GetArticles"](Client, arguments);
        }

        public virtual Task<List<Article>> GetArticlesAfter(int after,DeviceType deviceType)
        {
            var arguments = new object[] { after,deviceType };
            return (Task<List<Article>>) methodImpls["GetArticlesAfter"](Client, arguments);
        }

        public virtual Task<List<Article>> GetArticlesBefore(int before,DeviceType deviceType)
        {
            var arguments = new object[] { before,deviceType };
            return (Task<List<Article>>) methodImpls["GetArticlesBefore"](Client, arguments);
        }

        public virtual Task<List<Event>> GetEvents(DeviceType deviceType)
        {
            var arguments = new object[] { deviceType };
            return (Task<List<Event>>) methodImpls["GetEvents"](Client, arguments);
        }

        public virtual Task<List<Event>> GetEventsAfter(int after,DeviceType deviceType)
        {
            var arguments = new object[] { after,deviceType };
            return (Task<List<Event>>) methodImpls["GetEventsAfter"](Client, arguments);
        }

        public virtual Task<List<Event>> GetEventsBefore(int before,DeviceType deviceType)
        {
            var arguments = new object[] { before,deviceType };
            return (Task<List<Event>>) methodImpls["GetEventsBefore"](Client, arguments);
        }

        public virtual Task<List<ElectionArticle>> GetElectionArticles(DeviceType deviceType)
        {
            var arguments = new object[] { deviceType };
            return (Task<List<ElectionArticle>>) methodImpls["GetElectionArticles"](Client, arguments);
        }

        public virtual Task<List<ElectionArticle>> GetElectionArticlesAfter(int after,DeviceType deviceType)
        {
            var arguments = new object[] { after,deviceType };
            return (Task<List<ElectionArticle>>) methodImpls["GetElectionArticlesAfter"](Client, arguments);
        }

        public virtual Task<List<ElectionArticle>> GetElectionArticlesBefore(int before,DeviceType deviceType)
        {
            var arguments = new object[] { before,deviceType };
            return (Task<List<ElectionArticle>>) methodImpls["GetElectionArticlesBefore"](Client, arguments);
        }

    }
}


