// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Hdp.TouchRx
{
	public partial class DemoViewCell : UITableViewCell
	{
		public DemoViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
